services:
  jimdo.finder:
    class: Symfony\Component\Finder\Finder

  jimdo.file_locator:
    class: Jimdo\JimKanWall\ImportBundle\FileLocator\FileLocator
    arguments:
      - @jimdo.finder

  jimdo.import_runner:
    class: Jimdo\JimKanWall\ImportBundle\ImportRunner\ImportRunner
    arguments:
      - @jimdo.file_locator
