services:
  jimdo.file_loader:
    class: Jimdo\JimKanWall\ImportBundle\FileHandler\FileLoader

  jimdo.finder:
    class: Symfony\Component\Finder\Finder

  jimdo.file_locator:
    class: Jimdo\JimKanWall\ImportBundle\FileHandler\FileLocator
    arguments:
      - @jimdo.finder

  jimdo.import_runner:
    class: Jimdo\JimKanWall\ImportBundle\ImportRunner\ImportRunner
    arguments:
      - @jimdo.file_locator
      - @jimdo.file_loader
