JimdoJimKanWallViewBoardBundle:
    resource: "@JimdoJimKanWallViewBoardBundle/Controller/"
    type:     annotation
    prefix:   /

JimdoJimKanWallImportBundle:
    resource: "@JimdoJimKanWallImportBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
