JimdoJimFlowEditBoardBundle:
    resource: "@JimdoJimFlowEditBoardBundle/Controller/"
    type:     annotation
    prefix:   /

JimdoJimFlowViewBoardBundle:
    resource: "@JimdoJimFlowViewBoardBundle/Controller/"
    type:     annotation
    prefix:   /

JimdoJimFlowImportBundle:
    resource: "@JimdoJimFlowImportBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
