Jimdo\JimKanWall\ImportBundle\Entity\Board:
  type: entity
  repositoryClass: Jimdo\JimKanWall\ImportBundle\Entity\BoardRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
  oneToMany:
    boardColumns:
      targetEntity: BoardColumn
      mappedBy: board
    boardSnapShots:
      targetEntity: SnapShot
      mappedBy: board
  lifecycleCallbacks: {  }
