services:
  jimdo.entity_to_view_mapper:
    class: Jimdo\JimKanWall\ViewBoardBundle\Mapper\EntityToViewMapper
    arguments:
      - @doctrine.orm.entity_manager
      - @jimdo.snapshot_model
      - @jimdo.board_model
      - @jimdo.column_factory
      - @jimdo.caching_ticket_provider_decorator

  jimdo.snapshot_model:
    class: Jimdo\JimKanWall\ViewBoardBundle\Model\SnapShotModel

  jimdo.board_model:
    class: Jimdo\JimKanWall\ViewBoardBundle\Model\BoardModel

  jimdo.column_factory:
    class: Jimdo\JimKanWall\ViewBoardBundle\Model\ColumnModelFactory

  jimdo.caching_ticket_provider_decorator:
    class: Jimdo\JimKanWall\ViewBoardBundle\Model\CachingTicketProviderDecorator
    arguments:
      - @jimdo.routing_ticket_provider_decorator

  jimdo.routing_ticket_provider_decorator:
    class: Jimdo\JimKanWall\ViewBoardBundle\Model\RoutingTicketProviderDecorator
    arguments:
      - @jimdo.trac_ticket_provider

  jimdo.trac_ticket_provider:
    class: Jimdo\JimKanWall\ViewBoardBundle\Model\TracTicketProvider
    arguments:
      - @jimdo.ticket_model

  jimdo.ticket_model:
    class: Jimdo\JimKanWall\ViewBoardBundle\Model\TicketModel