<?php

namespace Jimdo\JimKanWall\ImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoardColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardColumnRepository extends EntityRepository
{
    public function getFilledColumnsByBoardIdAndSnapshotIdOrderedAsc($boardId, $snapshotId)
    {
        $qb = $this->createQueryBuilder('bc')
                   ->select('bc, tc')
                   ->leftJoin('bc.ticketsToColumn', 'tc')
                   ->where('tc.snapShot = ?2')
                   ->orWhere('tc.snapShot is null')
                   ->andWhere('bc.board = ?1')
                   ->setParameter(1, $boardId)
                   ->setParameter(2, $snapshotId)
                   ->addOrderBy('bc.ordering', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function getColumnsByBoardIdOrderedAsc($board_id)
    {
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.board = ?1')
                ->setParameter(1, $board_id)
                ->addOrderBy('b.ordering', 'ASC');

        return $qb->getQuery()->getResult();
    }
}