<?php

namespace Jimdo\JimKanWall\ImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketToColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketToColumnRepository extends EntityRepository
{
    public function getTicketInSnapShot($code, $snapShotId)
    {
        $qb = $this->createQueryBuilder('tc')
                   ->select('tc')
                   ->leftJoin('tc.snapShot', 's')
                   ->where('s.id = ?1')
                   ->andWhere('tc.id = ?2')
                   ->setMaxResults(1)
                   ->setParameter('1', $snapShotId)
                   ->setParameter('2', $code);

        return $qb->getQuery()->getOneOrNullResult();
    }
}