services:
  jimdo.entity_to_view_mapper:
    class: Jimdo\JimFlow\ViewBoardBundle\Mapper\EntityToViewMapper
    arguments:
      - @doctrine.orm.entity_manager
      - @jimdo.snapshot_model
      - @jimdo.board_model
      - @jimdo.column_factory
      - @jimdo.caching_ticket_provider_decorator

  jimdo.snapshot_model:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\SnapShotModel

  jimdo.board_model:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\BoardModel

  jimdo.column_factory:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\ColumnModelFactory

  jimdo.caching_ticket_provider_decorator:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\CachingTicketProviderDecorator
    arguments:
      - @jimdo.routing_ticket_provider_decorator

  jimdo.routing_ticket_provider_decorator:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\RoutingTicketProviderDecorator
    arguments:
      - @jimdo.trac_ticket_provider
      - @jimdo.default_ticket_provider
      - @jimdo.jira_ticket_provider

  jimdo.trac_ticket_provider:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\TracTicketProvider
    arguments:
      - @jimdo.ticket_factory
      - @zend.xml_rpc_client
      - %trac_url%

  jimdo.jira_ticket_provider:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\JiraTicketProvider
    arguments:
      - @jimdo.ticket_factory
      - %jira_protocol%
      - %jira_url%
      - %jira_user%
      - %jira_password%
      
  jimdo.default_ticket_provider:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\DefaultTicketProvider
    arguments:
      - @jimdo.ticket_factory
      
  jimdo.ticket_factory:
    class: Jimdo\JimFlow\ViewBoardBundle\Model\TicketFactory

  zend.xml_rpc_client:
    class: Zend\XmlRpc\Client
    arguments:
      - "https://%trac_user%:%trac_password%@%trac_url%/trac/login/xmlrpc"